import {
  STELLAR_HORIZON_URL as CONFIGURED_STELLAR_HORIZON_URL,
  STELLAR_NETWORK_PASSPHRASE as CONFIGURED_STELLAR_NETWORK_PASSPHRASE,
  STELLAR_RPC_URL as CONFIGURED_STELLAR_RPC_URL,
  ESCROW_CONTRACT_ID,
  REPUTATION_CONTRACT_ID,
  STABLECOIN_TOKEN_CONTRACT_ID,
} from "@/core/config/stellar-contracts.ts";
import { WALLET_NETWORK } from "@/core/wallet/config";

export const STELLAR_NETWORK = WALLET_NETWORK;
export const STELLAR_NETWORK_PASSPHRASE = CONFIGURED_STELLAR_NETWORK_PASSPHRASE;
export const STELLAR_RPC_URL = CONFIGURED_STELLAR_RPC_URL;
export const STELLAR_HORIZON_URL = CONFIGURED_STELLAR_HORIZON_URL;
export const REPUTATION_CONTRACT = REPUTATION_CONTRACT_ID;
export const ESCROW_CONTRACT = ESCROW_CONTRACT_ID;
export const STABLECOIN_TOKEN_CONTRACT = STABLECOIN_TOKEN_CONTRACT_ID;
