import {
  STELLAR_TESTNET_HORIZON_URL,
  STELLAR_TESTNET_NETWORK_PASSPHRASE,
  STELLAR_TESTNET_RPC_URL,
  WALLET_NETWORK,
} from "@/core/wallet/config";

export const STELLAR_NETWORK = WALLET_NETWORK;
export const STELLAR_NETWORK_PASSPHRASE = STELLAR_TESTNET_NETWORK_PASSPHRASE;
export const STELLAR_RPC_URL = STELLAR_TESTNET_RPC_URL;
export const STELLAR_HORIZON_URL = STELLAR_TESTNET_HORIZON_URL;
